name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Install frontend dependencies
      run: npm ci

    - name: Install backend dependencies
      run: cd server && npm ci

    - name: Run all frontend tests
      run: npm test -- --run

    - name: Build frontend
      run: npm run build

    - name: Test Docker build
      run: docker build -t test-image .