name: Cleanup PR Docker Images

on:
  # Run on PR close
  pull_request:
    types: [closed]
  
  # Run on schedule to clean up old images
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (do not delete images)'
        required: false
        default: 'true'
      days_to_keep:
        description: 'Keep images newer than this many days'
        required: false
        default: '1'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cleanup-pr-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Cleanup on PR close - delete images specific to this PR
      - name: Delete PR-specific images
        if: github.event_name == 'pull_request'
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Cleaning up images for closed PR #${PR_NUMBER}"
          
          # Get all versions for this package
          VERSIONS=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/user/packages/container/${IMAGE_NAME##*/}/versions" \
            --paginate \
            --jq '.[] | select(.metadata.container.tags[] | contains("pr-'${PR_NUMBER}'")) | .id')
          
          # Delete each version
          for VERSION_ID in $VERSIONS; do
            echo "Deleting version ${VERSION_ID} with PR tag pr-${PR_NUMBER}"
            if [[ "${{ github.event.inputs.dry_run }}" != "true" ]]; then
              gh api \
                --method DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "/user/packages/container/${IMAGE_NAME##*/}/versions/${VERSION_ID}"
            else
              echo "[DRY RUN] Would delete version ${VERSION_ID}"
            fi
          done

      # Scheduled/manual cleanup - delete old images (keep only today's)
      - name: Delete old images (except main and tagged)
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        env:
          DAYS_TO_KEEP: ${{ github.event.inputs.days_to_keep || '1' }}
          # For scheduled runs, default to actual deletion. For manual runs, use input (defaults to true)
          DRY_RUN: ${{ github.event_name == 'schedule' && 'false' || github.event.inputs.dry_run || 'true' }}
        run: |
          echo "============================================"
          echo "Cleanup Configuration:"
          echo "  - Days to keep: ${DAYS_TO_KEEP}"
          echo "  - Dry run: ${DRY_RUN}"
          echo "============================================"
          
          # Calculate cutoff date
          if [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS
            CUTOFF_DATE=$(date -v-${DAYS_TO_KEEP}d -u +"%Y-%m-%dT%H:%M:%SZ")
          else
            # Linux
            CUTOFF_DATE=$(date -u -d "${DAYS_TO_KEEP} days ago" +"%Y-%m-%dT%H:%M:%SZ")
          fi
          
          echo "Cutoff date: ${CUTOFF_DATE}"
          echo "Current date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          echo "Will delete all images created before ${CUTOFF_DATE}"
          echo "Will preserve: main, latest, and version tags (v*)"
          echo ""
          
          # Get all versions
          VERSIONS=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/user/packages/container/${IMAGE_NAME##*/}/versions" \
            --paginate \
            --jq '.[]')
          
          # Process each version
          DELETE_COUNT=0
          SKIP_COUNT=0
          
          echo "$VERSIONS" | jq -c '.' | while read -r VERSION; do
            VERSION_ID=$(echo "$VERSION" | jq -r '.id')
            CREATED_AT=$(echo "$VERSION" | jq -r '.created_at')
            TAGS=$(echo "$VERSION" | jq -r '.metadata.container.tags[]' 2>/dev/null || echo "")
            
            # Create a tags array for easier checking
            TAG_LIST=""
            for TAG in $TAGS; do
              TAG_LIST="${TAG_LIST} ${TAG}"
            done
            
            # Check if it has protected tags (latest, main, or version tags)
            PROTECTED=false
            for TAG in $TAGS; do
              if [[ "$TAG" == "latest" ]] || [[ "$TAG" == "main" ]] || [[ "$TAG" =~ ^v[0-9] ]]; then
                PROTECTED=true
                break
              fi
            done
            
            if [[ "$PROTECTED" == "true" ]]; then
              echo "✓ KEEPING version ${VERSION_ID} - Protected tags: ${TAG_LIST}"
              ((SKIP_COUNT++))
              continue
            fi
            
            # Check if older than cutoff (delete all non-protected images older than cutoff)
            if [[ "$CREATED_AT" < "$CUTOFF_DATE" ]]; then
              echo "✗ DELETING version ${VERSION_ID} - Created: ${CREATED_AT}, Tags: ${TAG_LIST}"
              ((DELETE_COUNT++))
              
              if [[ "${DRY_RUN}" != "true" ]]; then
                gh api \
                  --method DELETE \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  "/user/packages/container/${IMAGE_NAME##*/}/versions/${VERSION_ID}" || true
              else
                echo "  [DRY RUN] Would delete this version"
              fi
            else
              echo "✓ KEEPING version ${VERSION_ID} - Recent (${CREATED_AT}), Tags: ${TAG_LIST}"
              ((SKIP_COUNT++))
            fi
          done
          
          echo ""
          echo "============================================"
          echo "Summary:"
          echo "  - Images to delete: ${DELETE_COUNT}"
          echo "  - Images to keep: ${SKIP_COUNT}"
          echo "  - Dry run: ${DRY_RUN}"
          echo "============================================"

      # Report on remaining images
      - name: Report remaining images
        if: always()
        run: |
          echo "## Container Registry Status" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Get current package versions
          VERSIONS=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/user/packages/container/${IMAGE_NAME##*/}/versions" \
            --paginate)
          
          TOTAL_COUNT=$(echo "$VERSIONS" | jq '. | length')
          PROTECTED_COUNT=$(echo "$VERSIONS" | jq '[.[] | select(.metadata.container.tags[] | test("^(latest|main|v[0-9])"))] | length')
          PR_COUNT=$(echo "$VERSIONS" | jq '[.[] | select(.metadata.container.tags[] | test("^pr-"))] | length')
          SHA_COUNT=$(echo "$VERSIONS" | jq '[.[] | select(.metadata.container.tags[] | test("^sha-"))] | length')
          
          echo "### Image Statistics" >> $GITHUB_STEP_SUMMARY
          echo "| Type | Count |" >> $GITHUB_STEP_SUMMARY
          echo "|------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Total images | ${TOTAL_COUNT} |" >> $GITHUB_STEP_SUMMARY
          echo "| Protected (main/latest/versions) | ${PROTECTED_COUNT} |" >> $GITHUB_STEP_SUMMARY
          echo "| PR images | ${PR_COUNT} |" >> $GITHUB_STEP_SUMMARY
          echo "| SHA-tagged images | ${SHA_COUNT} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # List all remaining images grouped by type
          echo "### Protected Images (will never be deleted):" >> $GITHUB_STEP_SUMMARY
          echo "$VERSIONS" | jq -r '.[] | 
            select(.metadata.container.tags[] | test("^(latest|main|v[0-9])")) | 
            "- **\(.metadata.container.tags | join(", "))** (created: \(.created_at))"' >> $GITHUB_STEP_SUMMARY
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Recent Images (from today):" >> $GITHUB_STEP_SUMMARY
          TODAY=$(date -u +"%Y-%m-%d")
          echo "$VERSIONS" | jq -r --arg today "$TODAY" '.[] | 
            select(.created_at | startswith($today)) | 
            select(.metadata.container.tags[] | test("^(latest|main|v[0-9])") | not) |
            "- \(.metadata.container.tags | join(", ")) (created: \(.created_at))"' >> $GITHUB_STEP_SUMMARY