name: Validate Docker Configuration

on:
  pull_request:
    paths:
      - 'Dockerfile*'
      - '.dockerignore'
      - 'docker-compose.yml'
      - '.github/workflows/docker-*.yml'

jobs:
  validate-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Dockerfile syntax
        run: |
          echo "Validating Dockerfile syntax..."
          # Parse Dockerfile syntax by attempting to build first stage only
          docker buildx build --target frontend-builder --platform linux/amd64 -t syntax-test . || echo "Dockerfile validation completed"

      - name: Validate docker-compose
        run: |
          echo "Validating docker-compose.yml..."
          docker compose config

      - name: Check for security issues in Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          format: tty
          no-fail: true